# Model Parameters
model_params: {
    model_config: {
        name: "GaussianLoDModel",
        kwargs: {
            gs_attr: "explicit2D", 
            color_attr: "SH2", 
            visible_threshold: 0.01,
            base_layer: 11,
            dist_ratio: 0.999,
            render_mode: "RGB+ED",
        }
    },
    source_path: "/path/to/your/source_path",
    dataset_name: "your_dataset_name",
    scene_name: "your_scene_name", 
    resolution: -1,
    white_background: False,
    random_background: False,
    resolution_scales: [1.0],
    data_device: "cpu",
    eval: True,
    ratio: 1,
    data_format: city,
    llffhold: 32, 
    add_mask: True,
    add_depth: True,
}

# Pipeline Parameters
pipeline_params: {
    vis_step: 5000,
    add_prefilter: False,
}

# Optimization Parameters
optim_params: {
    iterations: 40_000,
    position_lr_init: 0.0,
    position_lr_final: 0.0,
    position_lr_delay_mult: 0.01,
    position_lr_max_steps: 40_000,
    
    offset_lr_init: 0.001,
    offset_lr_final: 0.00001,
    offset_lr_delay_mult: 0.01,
    offset_lr_max_steps: 40_000,

    feature_lr: 0.0025,
    opacity_lr: 0.05,
    scaling_lr: 0.005,
    rotation_lr: 0.001,

    lambda_dssim: 0.2,
    lambda_dreg: 0.0,

    lambda_normal: 0.0,
    normal_start_iter: 7_000,
    lambda_dist: 0.0,
    dist_start_iter: 3_000,

    start_depth: 500,
    depth_l1_weight_init: 1.000000,
    depth_l1_weight_final: 0.010000,
    
    progressive: True,
    coarse_iter: 10000,
    coarse_factor: 1.5,

    start_stat: 0,
    update_from: 500,
    update_interval: 300,
    update_until: 25000,
    min_opacity: 0.005,
    success_threshold: 0.8,
    densify_grad_threshold: 0.015,
    update_ratio: 0.2,
    extra_ratio: 0.25,
    extra_up: 0.02,
    overlap: True,
    densification: True,
    growing_strategy: "max",
}