# Model Parameters
model_params: {
    model_config: {
        name: "GaussianLoDModel",
        kwargs: {
            max_sh_degree: 3,
            padding: 0.0,
            n_offsets: 1,
            fork: 2, 
            visible_threshold: 0.9,
            dist2level: 'round',
            base_layer: 11,
            progressive: True,
            extend: 1.1,
            dist_ratio: 0.999,
            levels: -1, 
            init_level: -1,
        }
    },
    base_model: "2dgs",
    source_path: "/nas/shared/pjlab_lingjun_landmarks/yumulin_group/nerf_data/mipnerf360/bicycle",
    dataset_name: "mipnerf360",
    scene_name: "bicycle", 
    images: "images",
    resolution: -1,
    white_background: False,
    random_background: False,
    resolution_scales: [1.0],
    data_device: "cuda",
    eval: True,
    ratio: 1,
    render_mode: "RGB+ED",
}

# Pipeline Parameters
pipeline_params: {
    compute_cov3D_python:  False,
    convert_SHs_python: False,
    debug:  False,
}


# Optimization Parameters
optim_params: {
    iterations: 40_000,
    position_lr_init: 0.0,
    position_lr_final: 0.0,
    position_lr_delay_mult: 0.01,
    position_lr_max_steps: 40_000,
    
    offset_lr_init: 0.01,
    offset_lr_final: 0.0001,
    offset_lr_delay_mult: 0.01,
    offset_lr_max_steps: 40_000,

    feature_lr: 0.0025,
    opacity_lr: 0.05,
    scaling_lr: 0.005,
    rotation_lr: 0.001,

    lambda_dssim: 0.2,
    lambda_dreg: 0.0,

    lambda_normal: 0.05,
    normal_start_iter: 7_000,
    lambda_dist: 0.0,
    dist_start_iter: 3_000,
    
    start_stat: 500,
    update_from: 1500,
    coarse_iter: 10000,
    coarse_factor: 1.5,
    update_interval: 100,
    update_until: 25000,
    overlap: True,
    densification: True,

    min_opacity: 0.005,
    success_threshold: 0.8,
    densify_grad_threshold: 0.0002,
    update_ratio: 0.2,
    extra_ratio: 0.25,
    extra_up: 0.02,
}